### ISSUE TITLE
Contact Us Revision

### ISSUE THREAD

**Issue by LevianthProject** [Minilemon-Official-Team/website-company-profile#41]
- [x] All Title diubah menjadi image title
- [ ] Dibuat full size desktop, bisa buat bagian contact us container dan sosmed container dibuat 45% 45% height screen size dan 10% untuk footer nya

**Comment by muchfahmiarif** [comment]
> * [x]  All Title diubah menjadi image title
> * [ ]  Dibuat full size desktop, bisa buat bagian contact us container dan sosmed container dibuat 45% 45% height screen size dan 10% untuk footer nya

ghaz @LevianthProject point no 2 sepertinya tidak bisa di impelemntasi untuk saat ini karna perlu rubat layout lagi

**Comment by gilanggger** [comment]
iya kak
